tests:
  stage: test
  image: python:3.8-slim-buster
  services:
    - mongo:4.2.1
  variables:
    TWITCHCANCER_CONFIGFILE: twitchcancer/config.ci.yml
  script:
    - pip install -e .[dev]
    - nosetests
    - flake8
