version: '3'

networks:
  internal:
    external: false
  web:
    external: true

services:
  monitor:
    container_name: twitchcancer_monitor
    build: .
    image: ${TWITCHCANCER_IMAGE}
    restart: always
    command: twitchcancer-monitor
    environment:
      - TWITCHCANCER_CONFIGFILE
    volumes:
      - ./var/config/:/var/app/var/config/
    networks:
      - web
    expose:
      - "29001"
      - "29002"
  record:
    container_name: twitchcancer_record
    image: ${TWITCHCANCER_IMAGE}
    restart: always
    command: twitchcancer-record
    environment:
      - TWITCHCANCER_CONFIGFILE
    networks:
      - internal
    depends_on:
      - mongo
      - monitor
    links:
      - mongo
      - monitor
    volumes:
      - ./var/config/:/var/app/var/config/
  expose:
    container_name: twitchcancer_expose
    image: ${TWITCHCANCER_IMAGE}
    restart: always
    command: twitchcancer-expose
    environment:
      - TWITCHCANCER_CONFIGFILE
    volumes:
      - ./var/config/:/var/app/var/config/
      - ${CANCERINO_CERTS}:/var/app/var/ssl/
    networks:
      - internal
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    container_name: twitchcancer_mongo
    image: ${MONGO_IMAGE}
    restart: always
    volumes:
      - ./var/data/mongodb:/data/db
    networks:
      - internal
    expose:
      - "27017"