#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import logging
logger = logging.getLogger('twitchcancer')

from twitchcancer.config import Config
from twitchcancer.utils.logging import setup_logger
from twitchcancer.api.api import run

if __name__ == "__main__":
  parser = argparse.ArgumentParser()

  parser.add_argument('--log', dest='loglevel',
    help="set the level of messages to display")

  parser.add_argument('-f', '--config', dest='config',
    help="load configuration from this file")

  args = parser.parse_args()

  # load the config
  if args.config:
    Config.load(args.config)

  # set the logging stack up
  setup_logger(logger, args.loglevel, Config, "expose.log")

  # start running the api forever
  logger.debug("Started")
  run(args)
